### ISSUE TITLE
Favicon should be changed with timy icon

### ISSUE THREAD

**Issue by inovramadani** [forstek/timy-dashboard#43]

**Comment by Angg** [comment]
@inovramadani on my browser (chrome and firefox) the favicon already changed with timy icon. What browser do you use?

![timy-chrome](https://user-images.githubusercontent.com/11014352/76386381-f7b06c00-6396-11ea-8ec4-6cb8c8382be2.png)
![timy-firefox](https://user-images.githubusercontent.com/11014352/76386397-ff701080-6396-11ea-8997-961ba636fe8d.png)
